# Generated by Django 3.0.6 on 2020-05-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
